version: '3.9'
networks:
  default:
    name: 'rds-databases'
services:
  mongo:
    image: mongo:6.0.1
    container_name: 'mongo'
    volumes:
      - mongo_data:/mongodb/data/db
      - ./initdb.js:/docker-entrypoint-initdb.d/initdb.js
    env_file:
      - './database.env'
    restart: unless-stopped
    ports:
      - "27017:27017"
volumes:
  mongo_data: